// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'api key ',
    appId: '1:218772837194:web:775f7921a1addc9d8027b3',
    messagingSenderId: '218772837194',
    projectId: 'minimalistwardrobe-f0509',
    authDomain: 'minimalistwardrobe-f0509.firebaseapp.com',
    storageBucket: 'minimalistwardrobe-f0509.firebasestorage.app',
    measurementId: 'G-9NTKKBFP9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api key',
    appId: '1:218772837194:android:5d1c4cf3a1afc94c8027b3',
    messagingSenderId: '218772837194',
    projectId: 'minimalistwardrobe-f0509',
    storageBucket: 'minimalistwardrobe-f0509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'api key',
    appId: '1:218772837194:ios:22e2f12b4ca9cfe28027b3',
    messagingSenderId: '218772837194',
    projectId: 'minimalistwardrobe-f0509',
    storageBucket: 'minimalistwardrobe-f0509.firebasestorage.app',
    iosClientId: '218772837194-25asa7ibofnhuen7j9o5f2b5o448mrs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.modaDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'api key',
    appId: '1:218772837194:ios:22e2f12b4ca9cfe28027b3',
    messagingSenderId: '218772837194',
    projectId: 'minimalistwardrobe-f0509',
    storageBucket: 'minimalistwardrobe-f0509.firebasestorage.app',
    iosClientId: '218772837194-25asa7ibofnhuen7j9o5f2b5o448mrs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.modaDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'api key',
    appId: '1:218772837194:web:f0815ded21f958678027b3',
    messagingSenderId: '218772837194',
    projectId: 'minimalistwardrobe-f0509',
    authDomain: 'minimalistwardrobe-f0509.firebaseapp.com',
    storageBucket: 'minimalistwardrobe-f0509.firebasestorage.app',
    measurementId: 'G-M15TMFRZ9K',
  );
}
